~Config
WarpSystem:
  Maintenance: false
  Admin:
    Permission: 'WarpSystem.Admin'

  GUI:
    Admin:
      # The number must be between inclusive 9 and inclusive 54 and must be divisible by 9.
      Size: 54
      Title:
        Standard: '&c&l&nWarps&r'
        In_Category: '&c&l&nWarps&r &c@%CATEGORY%'
    User:
      # The number must be between inclusive 9 and inclusive 54 and must be divisible by 9.
      Size: 54
      Title:
        Standard: '&c&l&nWarps&r'
        In_Category: '&c&l&nWarps&r &c@%CATEGORY%'

  Teleport:
    Animation_After_Teleport:
      Enabled: true
    Op_Can_Skip_Delay: false
    Delay: 5
    # Animations:
    # 0  - FIREWORKS_SPARK
    # 1  - SUSPENDED_DEPTH
    # 2  - CRIT
    # 3  - CRIT_MAGIC
    # 4  - SMOKE_NORMAL
    # 5  - SMOKE_LARGE
    # 6  - SPELL
    # 7  - SPELL_INSTANT
    # 8  - SPELL_MOB
    # 9  - SPELL_WITCH
    # 10 - DRIP_WATER
    # 11 - DRIP_LAVA
    # 12 - VILLAGER_ANGRY
    # 13 - VILLAGER_HAPPY
    # 14 - TOWN_AURA
    # 15 - NOTE
    # 16 - ENCHANTMENT_TABLE
    # 17 - FLAME
    # 18 - CLOUD
    # 19 - REDSTONE
    # 20 - SNOW_SHOVEL
    # 21 - HEART
    # 22 - PORTAL
    Animation: 17
    Allow_Move: false

  Send:
    Teleport_Message:
      Warps: true
      SimpleWarps: true
      GlobalWarps: true
      NativePortals: true
      Portals: true
      WarpSigns: true
      TempWarps: true
      CommandBlocks: true
    Teleport_Cancel_Message: true

  Functions:
    Warps: true
    SimpleWarps: true
    Portals: true
    NativePortals: true
    WarpSigns: true
    GlobalWarps: true
    Shortcuts: true
    TempWarps: true
    #Available commands: '/warp <warp>' or '/globalwarp <warp>'
    #Activates when a player is within 5 blocks of a CommandBlock and the CommandBlock is active
    CommandBlocks: true

  TempWarps:
    #Permission to set the available amount of TempWarps: "WarpSystem.TempWarps.2" (Example for a maximum of 2 TempWarps)
    Time:
      #sec, min, hour, day
      Interval: min
      #Step to increase/decrease the duration in the gui
      DurationSteps: 5
      Min_Time: 5
      Max_Time: 1440
    # When a TempWarp expires, then it's inactive. (When "Time_After_Expiration" is expired too, the TempWarp will be deleted.)
    Inactive:
      # Time in seconds after an expiration. After that time, the TempWarp will be deleted.
      Time_After_Expiration: 60
      # Time in seconds to remind a player, if a TempWarp is inactive
      Reminds:
      - 30
      - 10
      - 5
    Name:
      Edit_Costs: 50
    Refund: true
    Message:
      Min_character_length: 5
      Max_character_length: 50
      Refund_by_removing_message: 0
      Edit_Costs: 50
    Custom_Teleport_Costs:
      Max_Costs: 500
      #Step to increase/decrease costs in gui
      Cost_Steps: 50
      #Percent of custom TeleportCosts
      TeleportCosts: 50
    Costs:
      CostsPerInterval: 5
      PublicCosts: 5
      MessageCosts: 5

  GlobalWarps:
    Use_Warps_Of_WarpsGUI: false

  Commands:
    Warp:
      #true: '/warp' opens the WarpGUI
      #false: '/warp <warp>' teleports you to warps
      GUI: false

  # true: block all commands of other plugin, which have this command
  # false: ignore
  Dominate_In_Commands:
    Highest_Priority:
      Warp: true
      Warps: true
      WarpSystem: true
      Portal: true
