WarpSystem:
  Language: ENG
  Admin:
    Permission: WarpSystem.Admin
  #If set to false, all players can use every user feature (admin tools still need op or modify permissions)
  #If set to true, all players must have certain user permissions such as 'WarpSystem.Use.WarpGUI'
  Permissions: true
  Command_Suggestions:
    Color: '&7'
    Argument: '&e'

  GUI:
    #false: The WarpGUI is identical on the entire server in all worlds
    #true: The WarpGUI is different in every world
    Bound_to_world: false
    Admin:
      #The number must be between inclusive 9 and inclusive 54 and must be divisible by 9.
      Size: 54
      Title:
        Standard: '&c&nWarps&r'
        In_Category: '&c&nWarps&r &c@%PAGE%'
    User:
      #The number must be between inclusive 9 and inclusive 54 and must be divisible by 9.
      Size: 54
      Title:
        Standard: '&c&nWarps&r'
        In_Category: '&c&nWarps&r &c@%PAGE%'

  Economy:
    Enabled: true
    Name: 'Coin(s)'
    #Priority list for economy systems
    #Available values: EXP, Essentials, Vault, GemsEconomy, PlayerPoints
    priority:
      - Essentials
      - Vault
      - GemsEconomy
      - PlayerPoints
      - EXP

  Teleport:
    Chunk_Pre_Loading:
      #If enabled, only players with the "WarpSystem.Teleport.ChunkPreLoading" will preload chunks!
      Limit_by_Permission: false
      Enabled: true
      Chunk_Radius: 1
    #Animations are only visible for players who see the teleporting player
    Public_Animations: true
    Animation_After_Teleport:
      Enabled: true
    Delay: 3
    Allow_Move: false

  Send:
    Teleport_Message:
      WarpGUI: true
      SimpleWarps: true
      GlobalWarps: true
      Shortcuts: true
      Portals: true
      WarpSigns: true
      CommandBlocks: true
      PlayerWarps: true
      Spawn: true
    Teleport_Cancel_Message: true

  Functions:
    WarpGUI: true
    SimpleWarps: true
    Portals: true
    WarpSigns: true
    GlobalWarps: true
    Shortcuts: true
    #Available commands: '/warp <warp>' or '/globalwarp <warp>'
    #Required for '/tp' command for CommandBlocks (CommandBlocks with tp commands inside don't work, if you turn this to false)
    CommandBlocks: true
    RandomTeleports: true
    TeleportCommand: true
    PlayerWarps: true
    Spawn: false

  #'TeleportCommand' in 'Functions' (above) have to be toggled to true as well, if you want to use this feature.
  TeleportCommands:
    Back:
      #Amount of temp. saved locations for the /back command
      #If set to '1', the plugin counts the position from which the /back command was executed
      History_Size: 1
      Enabled: true
    Tp: true
    TpAll: true
    TpToggle: true
    Tpa: true
    TpaHere: true
    TpaAll: true
    TpaToggle: true
    #Tpa, TpaHere& TpaAll: |true: Players on this server can receive/send teleport requests from/to other servers. |false: Players can only send TeleportRequests to players on this server
    #TpAll: Only players from servers with 'BungeeCord: true' will be teleported to you.
    BungeeCord: true
    TeleportRequests:
      #Teleport costs for a transportation via tpa or tpaHere; The teleported player has to pay
      Teleport_Costs: 0
      #In seconds
      ExpireDelay: 30

  Portals:
    #Max distance between particle and player - Don't use distances higher than 200! It will cause lags.
    ParticleDistance: 64
    #Holograms support PlaceholderAPI | Time format: "0d, 0h, 0m, 0s" - Unnecessary values can be removed (examples: "1d, 5m", "10s", "5h")!
    #A value of 0 disables hologram updates
    HologramUpdateInterval: 0h, 1m, 0s

  SimpleWarps:
    #Adds on every created warp the standard permission: 'WarpSystem.Warps.<WarpName>'
    Add_Permission_On_Creation: false
    #If toggled to true, every SimpleWarp get the permission "WarpSystem.SimpleWarp.<warp>" regardless whether a warp already has a permission or not
    #Names containing spaces (" ") will be modified with underlines ("_"). So the permission of the warp "Test test" will be "test_test".
    Overwrite_Permissions: false

  Commands:
    Warp:
      #true: '/warp' opens the WarpGUI
      #false: '/warp <warp>' teleports you to warps
      GUI: false

Do_Not_Edit:
  Last_Version: "0"