~Config
WarpSystem:
  Language: ENG
  Maintenance: false
  Admin:
    Permission: WarpSystem.Admin
  #If set to false, all players can use every user feature (admin tools still need op or modify permissions)
  #If set to true, all players must have certain user permissions such as 'WarpSystem.Use.WarpGUI'
  Permissions: true

  GUI:
    #false: The WarpGUI is identical on the entire server in all worlds
    #true: The WarpGUI is different in every world
    Bound_to_world: false
    Admin:
      #The number must be between inclusive 9 and inclusive 54 and must be divisible by 9.
      Size: 54
      Title:
        Standard: '&c&nWarps&r'
        In_Category: '&c&nWarps&r &c@%PAGE%'
    User:
      #The number must be between inclusive 9 and inclusive 54 and must be divisible by 9.
      Size: 54
      Title:
        Standard: '&c&nWarps&r'
        In_Category: '&c&nWarps&r &c@%PAGE%'

  Economy:
    #Priority list for economy systems
    priority:
    - Essentials
    - Vault

  Teleport:
    Chunk_Pre_Loading:
      #If enabled, only players with the "WarpSystem.Teleport.ChunkPreLoading" will preload chunks!
      Limit_by_Permission: false
      Enabled: true
      Chunk_Radius: 1
    Animation_After_Teleport:
      Enabled: true
    Delay: 3
    Allow_Move: true

  Send:
    Teleport_Message:
      WarpGUI: true
      SimpleWarps: true
      GlobalWarps: true
      NativePortals: true
      Portals: true
      WarpSigns: true
      CommandBlocks: true
      PlayerWarps: true
    Teleport_Cancel_Message: true

  Functions:
    WarpGUI: true
    SimpleWarps: true
    EffectPortals: true
    NativePortals: true
    WarpSigns: true
    GlobalWarps: true
    Shortcuts: true
    #Available commands: '/warp <warp>' or '/globalwarp <warp>'
    #Required for '/tp' command for CommandBlocks (CommandBlocks with tp commands inside don't work, if you turn this to false)
    CommandBlocks: true
    RandomTeleports: true
    TeleportCommand: true
    PlayerWarps: true

  #'TeleportCommand' in 'Functions' (above) have to be toggled to true as well, if you want to use this feature.
  TeleportCommands:
    Back:
      #Amount of temp. saved locations for the /back command
      #If set to '1', the plugin counts the position from which the /back command was executed
      History_Size: 1
      Enabled: true
    Tp: true
    TpAll: true
    TpToggle: true
    Tpa: true
    TpaHere: true
    TpaAll: true
    TpaToggle: true
    #Tpa, TpaHere& TpaAll: |true: Players on this server can receive/send teleport requests from/to other servers. |false: Players can only send TeleportRequests to players on this server
    #TpAll: Only players from servers with 'BungeeCord: true' will be teleported to you.
    BungeeCord: true
    TeleportRequests:
      #Teleport costs for a transportation via tpa or tpaHere; The teleported player has to pay
      Teleport_Costs: 0
      #In seconds
      ExpireDelay: 30
      #true: The teleport request SENDER will be notified about every accepted or denied teleport request. |false: The teleport request SENDER won't get any accept or deny messages
      Notify_TpaAll_Sender: true

  EffectPortals:
    #Max distance between particle and player - Don't use distances higher than 200! It will cause lags.
    ParticleDistance: 70.0

  SimpleWarps:
    #Adds on every created warp the standard permission: 'WarpSystem.Warps.<WarpName>'
    Add_Permission_On_Creation: false

  Commands:
    Warp:
      #true: '/warp' opens the WarpGUI
      #false: '/warp <warp>' teleports you to warps
      GUI: false

Do_Not_Edit:
  Last_Version: "0"
