# #####################################
# # Help:
# #   "Dominate_In_Commands" means the priority for one command.
# #
# #   For example: A player runs the "/warp"-command and your
# #   server has Essentials activated and this System.
# #   The server refer the command to the plugin, which was activated
# #   first.
# #   If you toggle the command "Warp" in this section to true, it
# #   will be run in every case and will blocks all other system in
# #   that moment.
# #
# #
# #
# #   Commands.Warp.GUI: Turn this to false, if you want to use this command for teleports ("/warp spawn"). If you turn this to 'true', the gui opens by running this command
# #####################################
WarpSystem:
  Maintenance: false
  Teleport:
    Op_Can_Skip_Delay: false
    Delay: 5
    Animation: 17
    Allow_Move: false
  Send:
    Teleport_Message: true
    Teleport_Cancel_Message: true
  Functions:
    Warps: true
    Portals: true
  Dominate_In_Commands:
    Highest_Priority:
      Warp: true
      Warps: true
      WarpSystem: true
      Portal: true
  Commands:
    Warp:
      GUI: false